parameters:
#    itk_koba.example.class: Itk\KobaBundle\Example

services:
#    itk_koba.example:
#        class: %itk_koba.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
